Repository chocoapp/dataeng-dagger, pull requests merged in 2023-01, with the labels that each got.

#3 Added new attribute supporting altering columns of infered redshift s…
  dagger/dag_creator/airflow/operator_creators/redshift_load_creator.py
  dagger/pipeline/tasks/redshift_load_task.py
Labels: size/M

#4 adding autocommit for alter columns command
  dagger/dag_creator/airflow/operator_creators/redshift_load_creator.py
Labels: size/XS

#6 adding autocommit for alter columns command
  dagger/dag_creator/airflow/operator_creators/redshift_load_creator.py
Labels: size/XS

#7 Switching to redshift sql operator from postgres operator
  dagger/dag_creator/airflow/operator_creators/redshift_load_creator.py
  dagger/dag_creator/airflow/operators/redshift_sql_operator.py
Labels: size/M

#10 Removing unneccessary parameter
  dagger/dag_creator/airflow/operator_creators/redshift_load_creator.py
Labels: size/XS

#8 Feature: dbt as Batch operator
  dagger/dag_creator/airflow/operator_creators/batch_creator.py
  dagger/dag_creator/airflow/operator_creators/dbt_creator.py
  dagger/dag_creator/airflow/operator_factory.py
  dagger/dag_creator/airflow/operators/awsbatch_operator.py
  dagger/pipeline/io_factory.py
  dagger/pipeline/task_factory.py
  dagger/pipeline/tasks/batch_task.py
  dagger/pipeline/tasks/dbt_task.py
  dagger/utilities/classes.py
  tests/utilities/test_classes.py
Labels: size/L

#11 Adding retry with tenacity
  dagger/dag_creator/airflow/operators/aws_athena_operator.py
  reqs/base.txt
Labels: size/XS

#12 Bump tenacity to match Airflow dependency packages requirements
  reqs/base.txt
Labels: size/XS
