Repository chocoapp/dataeng-dagger, pull requests merged in 2024-04, with the labels that each got.

#33 Feature/data 1791 defferable sensors
  .github/workflows/ci-data.yml
  Makefile
  dagger/conf.py
  dagger/dag_creator/airflow/dag_creator.py
  dagger/dag_creator/airflow/operator_creators/redshift_load_creator.py
  dagger/dag_creator/airflow/operator_creators/redshift_transform_creator.py
  dagger/dag_creator/airflow/operator_creators/redshift_unload_creator.py
  dagger/dag_creator/airflow/operators/postgres_operator.py
  dagger/dagger_config.yaml
  reqs/dev.txt
  reqs/test.txt
  setup.py
Labels: size/M

#35 feat: rename profile_name to target_name
  dagger/dag_creator/airflow/operator_creators/dbt_creator.py
  dagger/pipeline/tasks/dbt_task.py
  dockers/airflow/airflow.cfg
Labels: size/S

#36 Switching to official batch operator
  dagger/dag_creator/airflow/operator_creators/batch_creator.py
  dagger/dag_creator/airflow/operator_creators/spark_creator.py
  dagger/dag_creator/airflow/operators/awsbatch_operator.py
Labels: size/L

#38 fix: _get_model_data_location in DatabricksDBTConfigParser
  dagger/utilities/dbt_config_parser.py
  tests/fixtures/modules/dbt_config_parser_fixtures_databricks.py
Labels: size/S
